# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Blogs
    url: blog/
    weight: 20
  - name: Events
    url: events/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Uses
    url: uses/
    weight: 40
